services:
  postgres:
    image: postgres:18.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=snaphouse
      - POSTGRES_USER=snaphouse
      - POSTGRES_PASSWORD=passwd
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U snaphouse"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: {}
