// Code generated by cfgx. DO NOT EDIT.

package config

type DatabaseConfig struct {
	DSN string
}

type MediaConfig struct {
	AwsAccessKeyId     string
	AwsSecretAccessKey string
	BucketName         string
	Region             string
}

type UiApiConfig struct {
	CorsAllowedOrigins []string
	Port               int64
}

type UiConfig struct {
	Port int64
}

var (
	Database = DatabaseConfig{
		DSN: "postgres://snaphouse:passwd@localhost:5432/snaphouse?sslmode=disable",
	}
	Environment string = "development"
	Media              = MediaConfig{
		AwsAccessKeyId:     "",
		AwsSecretAccessKey: "",
		BucketName:         "snaphouse-in-media",
		Region:             "ap-south-1",
	}
	Ui = UiConfig{
		Port: 3000,
	}
	UiApi = UiApiConfig{
		CorsAllowedOrigins: []string{"http://localhost:3000"},
		Port:               3001,
	}
)
