// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID              int64
	EventID         int64
	CreatedByUserID pgtype.Int8
	UpdatedByUserID pgtype.Int8
	Name            string
	Description     pgtype.Text
	CoverImageUrl   pgtype.Text
	IsPublic        pgtype.Bool
	ShareUUID       pgtype.Text
	Passcode        pgtype.Text
	Created         int64
	Updated         int64
}

type AlbumView struct {
	ID        int64
	AlbumID   int64
	IPAddress pgtype.Text
	UserAgent pgtype.Text
	Referer   pgtype.Text
	ViewedAt  int64
}

type Event struct {
	ID              int64
	CreatedByUserID pgtype.Int8
	UpdatedByUserID pgtype.Int8
	Name            string
	Description     pgtype.Text
	CoverImageUrl   pgtype.Text
	ShareUUID       pgtype.Text
	Passcode        pgtype.Text
	Created         int64
	Updated         int64
}

type EventView struct {
	ID        int64
	EventID   int64
	IPAddress pgtype.Text
	UserAgent pgtype.Text
	Referer   pgtype.Text
	ViewedAt  int64
}

type MediaVariant struct {
	ID          int64
	MediaID     int64
	VariantType string
	Url         string
	Width       pgtype.Int4
	Height      pgtype.Int4
	FileSize    pgtype.Int8
	Created     int64
}

type Medium struct {
	ID        int64
	AlbumID   int64
	Url       string
	MediaType string
	FileSize  pgtype.Int8
	Created   int64
	Updated   int64
}

type Tenant struct {
	ID                int64
	ClerkOrgID        string
	WatermarkMediaUrl pgtype.Text
	WatermarkOpacity  pgtype.Numeric
	Created           int64
	Updated           int64
}

type User struct {
	ID          int64
	ClerkUserID string
	Created     int64
	Updated     int64
}
